"""Real-world pinned regression: LAGEOS-2 vs. an ILRS precise orbit.

The study Chunk 4 pin (docs/build-plan-real-world-validation.md; evidence in
``experiments/real-world-validation/lageos/``): propagate the pinned ILRS
truth state one day with the conservative force set and require the residual
to stay below the Checkpoint-A number times a generous margin. This guards the
class of bug internal tests structurally cannot see — self-consistent wiring
errors (a frame flip, a force that silently never reaches Orekit) — because
the truth orbit cannot share the misconception.

Fixture: t0 PV + hourly day-1 positions from the ESA ILRS weekly SP3
(satellite L52, SLR08 frame, 2023-04-16, V-records), emitted by
``run_lageos.py --emit-fixture``; provenance in the experiment README.

Tolerance policy (build-plan Chunk 4, binding): thresholds are the measured
values times margins generous enough to absorb orekit-data refreshes
(2019–2024 EOP is final history). They prove "the wiring didn't regress",
not "the number is exact". Measured (results.txt, 2026-07-12): t0 diff
9.3e-10 m; day-1 3D RMS 3.62 m.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from propygator import (
    Epoch,
    ForceModelConfig,
    Frame,
    IntegratorConfig,
    SpacecraftConfig,
    SpacecraftGeometry,
    State,
    TimeScale,
    propagate_numerical,
)

pytestmark = pytest.mark.usefixtures("orekit")

# --- pinned fixture generated by run_lageos.py --emit-fixture ---
# source: L52 (SLR08), see experiments/real-world-validation/lageos/README.md
T0_ISO = "2023-04-16T00:00:00"  # UTC, ITRF
T0_POS_M = (4648005.426, 10930211.971, -2102627.214)
T0_VEL_MS = (-2190.8290572, 1721.740385, 4489.0931494999995)
STEP_S = 3600.0  # truth sample spacing below (day 1, hourly)
TRUTH_POS_M = (
    (4648005.426, 10930211.971, -2102627.214),
    (-5965437.240999999, 4244867.575999999, 9553647.442),
    (-8378639.344, -8975108.399999999, -666787.798),
    (5225147.074, -5489987.264, -9631616.707999999),
    (10639985.286999999, 4867588.225000001, 2694513.444),
    (-5194878.415999999, 6671914.109999999, 8667712.879999999),
    (-11167805.116, -943697.794, -5143543.445),
    (3249589.429, -8813849.764, -7747834.83),
    (9571956.001, -2384406.449, 6814254.449),
    (-1042867.3510000001, 10750460.342, 5660382.494),
    (-7767378.331, 4539965.827, -8426641.182),
    (-3248472.508, -10940210.987, -4001624.942),
    (5893040.794, -4962829.050000001, 9218793.846),
    (7135852.585, 9898794.109000001, 1292670.4070000001),
    (-4700204.718, 5805641.23, -9751457.185999999),
    (-10251269.797999999, -6246336.034, 723762.1390000001),
    (4492618.062, -6229125.508, 9318722.229999999),
    (11623384.748, 2295122.8740000003, -3382682.522),
    (-3068793.3589999997, 7904148.906, -8788340.007000001),
    (-10621080.997, 1804920.919, 5265998.279),
    (1694442.288, -9707649.933, 7121188.931),
    (8810235.911, -4649720.867, -7272073.389),
    (2022349.5459999999, 10496090.280000001, -5729410.1790000005),
    (-6297253.066000001, 5688745.411, 8482372.771),
    (-5695546.46, -10352208.57, 3199119.631),
)

# LAGEOS-2 physical parameters (experiment README citations).
LAGEOS2_MASS_KG = 405.38
LAGEOS2_AREA_M2 = math.pi * 0.30**2
LAGEOS2_CR = 1.13

# Measured 9.3e-10 m — anything near a meter is a frame/time conversion bug.
T0_DIFF_BOUND_M = 1.0
# Measured 3.62 m RMS (Checkpoint A, tier-1 GO) — x4 margin.
DAY1_RMS_BOUND_M = 15.0


def test_lageos_conservative_day1_residual():
    t0 = Epoch.from_iso(T0_ISO, TimeScale.UTC)
    state0 = State(t0, np.array(T0_POS_M), np.array(T0_VEL_MS), Frame.ITRF).to_frame(
        Frame.EME2000
    )

    traj = propagate_numerical(
        state0,
        STEP_S * (len(TRUTH_POS_M) - 1),
        output_step=STEP_S,
        force_models=ForceModelConfig(
            drag=False, solid_tides=True, ocean_tides=True, relativity=True
        ),
        spacecraft=SpacecraftConfig(
            mass_kg=LAGEOS2_MASS_KG,
            geometry=SpacecraftGeometry.sphere(
                area_m2=LAGEOS2_AREA_M2, reflectivity_coefficient=LAGEOS2_CR
            ),
        ),
        integrator=IntegratorConfig.high_precision(),
        progress=False,
    )

    truth = np.asarray(TRUTH_POS_M)
    positions = traj.to_frame(Frame.ITRF).positions
    assert len(positions) == len(truth)
    d = np.linalg.norm(positions - truth, axis=1)

    # t0 sample isolates frame/time conversion from all dynamics.
    assert d[0] < T0_DIFF_BOUND_M
    # The conservative-force day-1 agreement (gravity + third body + SRP +
    # tides + relativity end-to-end against a measured orbit).
    rms = float(np.sqrt(np.mean(d**2)))
    assert rms < DAY1_RMS_BOUND_M
