"""The bundled Earth coastline basemap for map overlays (build-plan chunk 11a).

``_render_earth_basemap`` draws a low-resolution **Natural Earth 1:110m** coastline —
shipped as a committed asset, *no cartopy* — as a black ``LineCollection`` onto a
supplied matplotlib ``Axes``. The same lon/lat polylines drape the 3D ITRF Earth
sphere in ``plot_3d`` (chunk 11e), so both the 2D ground-track overlay and the 3D
view read this one asset (features.md §1.1 "Map machinery").

The asset (``data/coastline_110m.npz``, repo root) is loaded once and cached; it is
regenerated by ``scripts/generate_coastline.py`` (see ``data/README.md``). It stores a
single NaN-separated ``(K, 2)`` lon/lat array — ``[NaN, NaN]`` rows separate the
polylines, which :func:`_coastline_polylines` splits back apart for drawing.
"""

from __future__ import annotations

import logging
from functools import lru_cache
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
from matplotlib.collections import LineCollection

from .style import OUTLINE_COLOR

if TYPE_CHECKING:
    from matplotlib.axes import Axes
    from numpy.typing import NDArray

logger = logging.getLogger(__name__)

_COASTLINE_FILENAME = "coastline_110m.npz"
_COASTLINE_LINEWIDTH = 0.6


def _data_dir() -> Path:
    """Locate the repo-root ``data/`` directory holding bundled assets.

    Mirrors ``propagation.spacecraft._data_dir`` (the canonical asset-path resolver):
    ``plotting/`` depends only on ``core/`` plus its backend libraries, so this
    two-line helper is duplicated here rather than importing across the ``propagation``
    boundary. If a built wheel ever ships, move both repo-root assets into
    ``src/propygator/`` and switch to ``importlib.resources`` (see ``data/README.md``).
    """
    return Path(__file__).resolve().parents[3] / "data"


@lru_cache(maxsize=1)
def _coastline_lonlat() -> NDArray[np.float64]:
    """Load the cached NaN-separated ``(K, 2)`` lon/lat coastline array (read-only)."""
    path = _data_dir() / _COASTLINE_FILENAME
    if not path.is_file():
        raise FileNotFoundError(
            f"coastline asset not found at {path}. It is a committed asset under "
            f"data/; regenerate it with `python scripts/generate_coastline.py`."
        )
    with np.load(path) as npz:
        coastline = npz["coastline"].astype(np.float64, copy=False)
    coastline.setflags(write=False)  # shared cached array; guard against mutation
    return coastline


def _coastline_polylines() -> list[NDArray[np.float64]]:
    """Split the cached coastline into a list of ``(M, 2)`` lon/lat polylines.

    Polylines are separated by ``[NaN, NaN]`` rows in the asset; splitting on them
    lets each polyline draw as one unbroken line (rather than a single line wrapping
    across the map between unrelated coast segments).
    """
    lonlat = _coastline_lonlat()
    breaks = np.flatnonzero(np.isnan(lonlat[:, 0]))
    polylines: list[NDArray[np.float64]] = []
    start = 0
    for stop in (*breaks.tolist(), len(lonlat)):
        if stop > start:
            polylines.append(lonlat[start:stop])
        start = stop + 1
    return polylines


def _render_earth_basemap(
    ax: Axes,
    *,
    color: str = OUTLINE_COLOR,
    linewidth: float = _COASTLINE_LINEWIDTH,
    zorder: float = 1.0,
) -> LineCollection:
    """Draw the bundled coastline as a black ``LineCollection`` onto ``ax``.

    Adds the collection to ``ax`` and returns it. Does **not** set the axis limits or
    aspect — the caller owns the lon/lat extent (a ground-track caller typically pins
    ``xlim(-180, 180)`` / ``ylim(-90, 90)``). No cartopy: just the committed polylines.
    """
    polylines = _coastline_polylines()
    collection = LineCollection(
        polylines, colors=color, linewidths=linewidth, zorder=zorder
    )
    ax.add_collection(collection)
    return collection
